---
profiles:
  CPU + Load:
    plugins:
      - cpu-0
      - load
    splat: cpu+load
    order: 1
  Memory:
    plugins:
      - memory
      - swap
    splat: memory
    order: 2
  Disk Usage:
    plugins:
      - df
    splat: disk+usage
    order: 3
  Processes:
    plugins:
      - processes
    splat: processes
    order: 4
  Interfaces:
    plugins:
      - interface
    splat: interfaces
    order: 5
  Nginx:
    plugins:
      - nginx
    splat: nginx
    order: 6
    
# Commentaire toussa
azote:
  CPU + Load:
    plugins:
      - cpu-0
      - load
    splat: cpu+load
    order: 1
