---
databases:
  graphs:
    - mysqlnode1:
      - cpu-0
    - mysqlnode2:
      - cpu-0
    - mysqlpra:
      - cpu-0
www-related:
    graphs:
      - carbone:
        - interface
      - fluor:
        - interface
      - magnesium:
        - interface
      - mazerati:
        - interface
        - nginx
